Remove default mailer
ActionMailer is disabled in config/application.rb and having this class
in the project causes puma to crash in production with:

NameError: uninitialized constant ActionMailer